FROM ubuntu:16.04
MAINTAINER 245386003@qq.com
# COPY sources.list /etc/apt/sources.list
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y gcc-arm-none-eabi gdb-arm-none-eabi openocd telnet make vim

WORKDIR /home/
